In [3]:
import pandas as pd

df = pd.read_csv("train.txt", sep="\t", names=["head", "relation", "tail"])

df.head()

         head                                           relation       tail
0    /m/027rn               /location/country/form_of_government   /m/06cx9
1   /m/017dcd  /tv/tv_program/regular_cast./tv/regular_tv_app...  /m/06v8s0
2  /m/07s9rl0                 /media_common/netflix_genre/titles  /m/0170z3
3   /m/01sl1q  /award/award_winner/awards_won./award/award_ho...  /m/044mz_
4   /m/0cnk2q  /soccer/football_team/current_roster./sports/s...  /m/02nzb8

In [4]:
print("Shape of dataset:", df.shape)
df.info()

Shape of dataset: (272115, 3)
<class 'pandas.DataFrame'>
RangeIndex: 272115 entries, 0 to 272114
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   head      272115 non-null  str
 1   relation  272115 non-null  str
 2   tail      272115 non-null  str
dtypes: str(3)
memory usage: 6.2 MB

In [5]:
df.isnull().sum()

head        0
relation    0
tail        0
dtype: int64

In [6]:
df = df.dropna()

In [7]:
df = df.drop_duplicates()

In [8]:
df = df.reset_index(drop=True)

In [9]:
print("Unique Heads:", df["head"].nunique())
print("Unique Relations:", df["relation"].nunique())
print("Unique Tails:", df["tail"].nunique())

Unique Heads: 13781
Unique Relations: 237
Unique Tails: 13379

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure()
sns.countplot(y="relation", data=df, order=df["relation"].value_counts().index[:10])
plt.title("Top 10 Relations in Knowledge Graph")
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_head = LabelEncoder()
le_relation = LabelEncoder()
le_tail = LabelEncoder()

df["head_enc"] = le_head.fit_transform(df["head"])
df["relation_enc"] = le_relation.fit_transform(df["relation"])
df["tail_enc"] = le_tail.fit_transform(df["tail"])

df.head()

,head,relation,tail,head_enc,relation_enc,tail_enc
0,/m/027rn,/location/country/form_of_government,/m/06cx9,3437,122,7797
1,/m/017dcd,/tv/tv_program/regular_cast./tv/regular_tv_app...,/m/06v8s0,758,230,8048
2,/m/07s9rl0,/media_common/netflix_genre/titles,/m/0170z3,9015,140,677
3,/m/01sl1q,/award/award_winner/awards_won./award/award_ho...,/m/044mz_,2275,12,6136
4,/m/0cnk2q,/soccer/football_team/current_roster./sports/s...,/m/02nzb8,10502,200,4127

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Normalize ONLY head and tail
df[["head_enc","tail_enc"]] = scaler.fit_transform(
    df[["head_enc","tail_enc"]]
)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

X = df[["head_enc","tail_enc"]]
y = df["relation_enc"]   # keep original encoded values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

pred = model.predict(X_test)

print("Model Accuracy:", accuracy_score(y_test, pred))

Model Accuracy: 0.07590728312204822